Fix nuget pablishing and some documentation

diff --git a/.github/workflows/publish-nuget-manual.yml b/.github/workflows/publish-nuget-manual.yml
--- a/.github/workflows/publish-nuget-manual.yml
+++ b/.github/workflows/publish-nuget-manual.yml
@@ -17,7 +17,8 @@ on:
         default: '0'
 
 env:
-  PROJECT_PATH: 'Ama.CRDT/Ama.CRDT.csproj'
+  PROJECT_PATH_MAIN: 'Ama.CRDT/Ama.CRDT.csproj'
+  PROJECT_PATH_STREAMS: 'Ama.CRDT.Partitioning.Streams/Ama.CRDT.Partitioning.Streams.csproj'
   PACKAGE_OUTPUT_DIRECTORY: '${{ github.workspace }}/nuget'
 
 jobs:
@@ -29,12 +30,16 @@ jobs:
 
       - name: Check for unshipped APIs
         run: |
-          UNSHIPPED_API_FILE="Ama.CRDT/PublicAPI.Unshipped.txt"
-          if [ -f "$UNSHIPPED_API_FILE" ] && [ -s "$UNSHIPPED_API_FILE" ]; then
-            echo "Error: PublicAPI.Unshipped.txt is not empty, indicating unshipped APIs."
-            echo "To publish a stable release, first 'ship' these APIs by moving them to PublicAPI.Shipped.txt and clearing PublicAPI.Unshipped.txt."
-            exit 1
-          fi
+          check_unshipped() {
+            if [ -f "$1" ] && [ -s "$1" ]; then
+              echo "Error: $1 is not empty, indicating unshipped APIs."
+              echo "To publish a stable release, first 'ship' these APIs by moving them to PublicAPI.Shipped.txt and clearing PublicAPI.Unshipped.txt."
+              exit 1
+            fi
+          }
+          
+          check_unshipped "Ama.CRDT/PublicAPI.Unshipped.txt"
+          check_unshipped "Ama.CRDT.Partitioning.Streams/PublicAPI.Unshipped.txt"
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
@@ -63,7 +68,9 @@ jobs:
         run: dotnet test --configuration Release --no-build --verbosity normal -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}
 
       - name: Pack
-        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}
+        run: |
+          dotnet pack ${{ env.PROJECT_PATH_MAIN }} --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}
+          dotnet pack ${{ env.PROJECT_PATH_STREAMS }} --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}
 
       - name: List created packages
         run: ls -R ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
